language: generic

services:
  - docker

script:
  - make docker

deploy:
  provider: releases
  # https://github.com/settings/tokens
  # Add variable TOKEN in TravisCI settings
  api_key: $TOKEN
  file:
    - "build/programming-assignments.pdf"
  name: Версия от $(date +'%Y-%m-%d')
skip-cleanup: true